# Generated by Django 4.2.11 on 2024-11-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='tier',
            field=models.CharField(default='알거지', max_length=20),
        ),
    ]
