# Generated by Django 4.2.11 on 2024-11-21 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField()),
                ('cur_unit', models.TextField()),
                ('cur_nm', models.TextField()),
                ('ttb', models.TextField()),
                ('tts', models.TextField()),
            ],
        ),
    ]
